version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper #define explicitamente o nome do container
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 #Porta padrão do ZooKeeper
      ZOOKEEPER_TICK_TIME: 2000 #Tempo em que o ZooKeper vai fazer a verificação de metadados e outras configurações

  kafka:
    image: confluentinc/cp-server:7.2.1
    depends_on:
      - zookeeper #Dependência do Kafka para o ZooKeeper, essencial para o funcionamento do Kafka
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181' #Conexão com o ZooKeeper, cada broker do Kafka fala com o ZooKeeper para fins de configurar e manter o estado do cluster
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      # Configuração para o JMX, rodando com Java Agent. Enviando métricas para o Prometheus, convertendo de JMX para o formato que o Prometheus entende
      KAFKA_OPTS: "-javaagent:/jmx/jmx_prometheus_javaagent-0.3.1.jar=7071:/jmx/kafka-metrics.yml"
    volumes:
        - "./jmx/:/jmx"

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka:29092"
    depends_on:
      - kafka
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/:/etc/prometheus/"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"